spring.application.name=transrv


spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update

openai.api.key=${OPENAI_API_KEY:}

logging.file.name=logs/application.log

evolution.api.key=${EVOLUTION_API_KEY:}
app.evolution.instance-name=${APP_EVOLUTION_INSTANCE_NAME:}

spring.quartz.properties.org.quartz.plugin.triggHistory.class=org.quartz.plugins.history.LoggingTriggerHistoryPlugin
spring.quartz.properties.org.quartz.plugin.jobHistory.class=org.quartz.plugins.history.LoggingJobHistoryPlugin

